language: node_js
sudo: false
node_js:
  - 'lts/*'
  - 'node'

before_install:
  - npm i -g npm@latest

install:
  - npm ci
  - cd projects/ng-jsonapi && npm ci && cd ../..

script:
  - npm test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI
  - npm run lint

after_success:
  - cat ./coverage/ng-jsonapi/lcov.info | ./node_modules/coveralls/bin/coveralls.js
